COLOR 7, 1
CLS
LOCATE 12, 30
PRINT "Mozart's Sonata in C"

PLAY "c2 L4 e g < b. > l16 c d 12 c"
PLAY "> a 14 g > c < g l16 g f e f 12 e"
PLAY "< a8 l16 b > c d e f g a g f e d c < b a"
PLAY "g8 a b > c d e f g f e d c < b a g f8 g a b > c d e"
PLAY "f e d c < b a g f e8 fga b > c d e d c < b a g f e"
PLAY "d8 e f g a b > c# d < a b > c# d e f g"
PLAY "a b > c < b a g f e f g a g f e d"
PLAY "< L8 b MS > g e c ML d g MS e c"
PLAY "D4 g4 < g2 g2 > c4 e4 g2"
PLAY "l16 a g f e f e d c e d e d e d e d e d e d e d c d"
PLAY "c4 c < g > c e g e c e f d < b > d"
PLAY "c4 < c < g > c e g e c e f d < b> d c4 > c4 c2"



