CLS
LOCATE 10, 25
COLOR 9
PRINT "Bach's Suites for Violoncello"
LOCATE 12, 37
PRINT "Suite 1"
LOCATE 14, 31
PRINT "Movement 1, Prelude"
COLOR 0

PLAY "< < <"
PLAY "t170"
PLAY "ML"
PLAY "l8"


FOR t = 1 TO 2
PLAY "g > d b a b d b d <"
NEXT t

FOR t = 1 TO 2
PLAY "g > e > c < b > c < e > c < e <"
NEXT t

FOR t = 1 TO 2
PLAY "g > f# > c < b > c < f# > c < f# <"
NEXT t

PLAY "g > g b a b g b g < g > g b a b g b f# <"

PLAY "g > e  b a b g f# g e g f# g < b > d c# < b >"

PLAY "c# g a g a g a g c# g a g a g a g"

PLAY "f# a > d c# d < a g a f# a g a d f# e d <"
                                              
PLAY "e b > g f# g < b > g < b e b > g f# g < b > g < b"

PLAY "e > c# d e d c# < b f > g f# e > d c# < b a g"

PLAY "f# e d > d < a > d < f# a d e f# a g f# e d"

PLAY "g# d f e f d g# d b d f e f d g# d"

PLAY "c e a b > c < a e d c e a b > c < a f# e"

PLAY "d# f# d# f# a f# a f# d# f# d# f# a f# a f#"

PLAY "g f# e g f# g a f# g f# e d c < b a g"

PLAY "f# > c d c d c d c < f# > c d c d c d c <"

PLAY "g b > f e f < b > f < b g b > f e f < b > f < b"

PLAY "g > c e d e c e c < g > c e d e c e c <"

FOR i = 1 TO 2
PLAY "g > f# > c < b > c < f# > c < f# <"
NEXT i

' This is the end of page 1



PLAY "g > d b a b g f# e d c < b a g f# e d"

FOR t = 1 TO 2
PLAY "c# a > e f# g e f# g <"
NEXT t

FOR t = 1 TO 2
PLAY "c a > d e f# d e f# <"
NEXT t

PLAY "c a > d f# t 120 a > t 100 c# l2 d"

PLAY "p2"

PLAY "t170 l8"

PLAY "< < a b > c d e f# g"

PLAY "a f# d e f# g a b > c < a f# g a b > c d"

PLAY "e- d c# mn d ml d c < b > mn c ml c < a f# e d < a b > c <"

PLAY "d a > d f# a b > c < a b g d c < b g a b"

PLAY "d g b > d g a b g > c# < b a mn b- ml b- a g# mn a"

PLAY "ml a g f# mn g ml g e c# < b a > c# e g a > c# d c#"

PLAY "d < a f# e f# a d f# < a > d c# < b a g f# e"

PLAY "l4 d l8 > > c < b a g f# e d > c < b a g f# e d"

PLAY "c b a g f# e d c < b > a g f# e d c < b"

PLAY "a > g f# e f# a d a e a f# a g a e a"

PLAY "f# a d a g a e a f# a d a g a e a"

PLAY "f# a d a e a f # a g mn a a ml a b a d mn a"

PLAY "a ml a b a > c < a d a b a > c < a > d < a b a >" ' middle of 4th line from bottom

PLAY "c < a b a > c < mn a a ml a b mn a a ml a b a g mn a"

PLAY "a ml a g mn a a ml a f# a g a f# a g a e a"

PLAY "f# a d e f d f# d g d g# d a d b- d"

PLAY "b d > c < d > c# < d > d < d > e- < d > e < d > f < d > f# < d > "

FOR u = 1 TO 2
PLAY "g < b d b > g < b > g < b >"
NEXT u

FOR r = 1 TO 2
PLAY "g < a d a > g < a > g < a >"
NEXT r

PLAY "f# c < d > c f# c f# c"

PLAY "t150 f# c t120 < d > t100 c f# t120 l4 c f# l2 c"

                         
PLAY "< < t80 l2 g > t 120 l4 b > l1 g"




