CLS
PLAY "t110o2l12"
SCREEN 1
VIEW (0, 0)-(319, 199), 1
10 PLAY "o2l12n0gab>dcceddgf+gd<bgab>cdedc<babg"
20 PLAY "f+gadf+a>c<babgab>dcceddgf+gd<bgab"
30 PLAY "e>dc<bagdgf+gb>dgd<bgb>dl4g<b>cl2dl4dl2cl4<b"
40 PLAY "l12adef+aga>c<b>c<af+df+a>c<babgab>dcced"
50 PLAY "dgf+gd<bgabe>dc<bagdgf+gbab>dcceddgf+gd<bgab"
60 PLAY ">cdedc<babgf+gadf+a>c<babgab>dcceddgf+gd<bgab"
70 PLAY "e>dc<bagdgf+l2bl4>cl2dl4dl2cl4<bl12adef+aga>c<b"
80 PLAY ">c<af+df+a>c<babgab>dcceddgf+gd<bgabe>dc<bagdgf+"
90 PLAY "gbab>dcceddgf+gd<bgab>cdedc<babgf+gadf+a>c<ba"
100 PLAY "bgab>dcceddgf+gd<bgabe>dc<bagdgf+gb>dgd<bgb>c+"
110 PLAY "d<def+ag+g+baa>c<bbaecdef>dcd<bg+ef+g+"
120 PLAY "a>c<b>ceddfeeag+aec<ab>cfedc<baeag+"
130 PLAY "a>cean0n0l4dl12ecdegfgb-aa>c<b>c<afdef"
140 PLAY "egfgec<gab-a>c<b>c<afdefecdegf+gba"
150 PLAY "bgab>dcceddgf+gd<bgab>cdedc<babgf+def+aga>c<b"
160 PLAY ">c<af+df+a>c<babgab>dcceddgf+gd<bgabe>dc<bagdgf+"
170 PLAY "gb>dgd<bgb>dfd<bgb>dec<af+a>cd<bgegb>c<af+df+a>c<ba"
180 PLAY "bgab>dcceddgf+gd<bgab>cdedc<babgf+gadf+a>c<ba"
190 PLAY "bgab>dcceddgf+gd<bgabl11e>l10dl9c<l8bl7al6gl5dl4gl3f+l1g"


