CLS
PRINT "Welcome to the land of Zig.  You are a wanderer, and were exploring an area"
PRINT "high in the Wajoon Mountains, when you came across a small village.  You "
PRINT "begin a conversation with the local inn keeper."
PRINT
PRINT "Press any key to continue..."

CLS
PRINT "He tells you strange tales about a warlord named Sonx.  As legend has it, "
PRINT "he keeps a sword that was stolen from good King Jeb.  The ruler has"
PRINT "long been gone, but as the story goes, the one who finds the sword will "
PRINT "become king over all the land of Zig.  Intrigued, you inquire further, and"
PRINT "he hands you a peice of map that has a few strange characters on it. You"
PRINT "cannot read them, and you ask the inn keeper about the letters.  He does "
PRINT "not know what they say."
PRINT
PRINT "Press any key to continue..."

DO WHILE INKEY$ = ""
LOOP




