CLS
LOCATE 11, 35
COLOR 2
PRINT "Bach's Giga"
LOCATE 13, 27
COLOR 1
PRINT "From the Partita in B flat."
COLOR 0
FOR i = 1 TO 2
PLAY "t250"
PLAY "l8"
PLAY "ML"
1 PLAY "f < d b- < b- > d b- < < b- > > d b- > f < d b- >"
2 PLAY "g < e- b- a- e- b- g e- b- > g < e- b-"
3 PLAY "> c < e- a g- e- a f e- a > c < e- a"
4 PLAY "> d < f b- < b- > f b- < < b- > > f b- > d < f b-"
5 PLAY "> g < b- > d < a b- > d < l16 g a l8 g b- > d < f b- > d"  'The 2nd G in this measure is trilled.
6 PLAY "< e b- > c < g b- > c < c b- > c e < b- > c"
7 PLAY "f < a > c < g a > c < l16 f g l8 f a > c < e a > c"  'The 2nd F is trilled.
8 PLAY "< d a b- f a b- < b- > a b- > d < a b-"
9 PLAY "> e < g b- d- g b- c g b- > e < g b-"
10 PLAY "> f < f a- d- f a- c f a- > f < f a-"
11 PLAY "> g < e g d- e g c e g > g < e g"
12 PLAY "> a- < e f d- e f c e f > a- < e f"
13 PLAY "b d f < a- > d f < g > d f b d f"
14 PLAY "> c < e g < d- > e g < c > e g b- e g"
15 PLAY "a- e f < b > e f c e f < c > e f"
16 PLAY "< < f > a > c f a > c l2 f"

PLAY "P4"

NEXT i

FOR u = 1 TO 2
17 PLAY "l8 a < f > c < e- f > c < < f > f > c a < f > c"
18 PLAY "b- < f > d < a- f > d < < b-  > f > d b- < f > d"
19 PLAY "g < e- > d < b- e- > d < a e- > c g < e- > c"
20 PLAY "f# < d > c < g e > c < a f# > c f# < a > c"
21 PLAY "g < g b- e- g b- d g b- > g < g b- "
22 PLAY "> a < f# a e- f# a d f# a > a < f# a"
23 PLAY "> b- < f# g e- f# g d f# g > b- < f# g"
24 PLAY " > > c < < f# a e- f# a d f# a > > c < < f# a"
25 PLAY "> b- < g b- > f# < a > c g < b- > d c# < g > e"
26 PLAY "d < a > f# < g b- > g <f# > c a < e- > c f#"
27 PLAY "< d b > g < c# b- > e < d a > f# < < d > > c f#"
28 PLAY "< < < g > > b- > g < < d > b- > g < < g > b- > g < < b- > b- > g"
29 PLAY "< d a- > f < f a- > f < b- a- > f d < a- > f"
30 PLAY "< e- g > e- < b- g > e- g < g > e- < d g > e-"
31 PLAY "< c a > e- < f a > e- < < b- > b- > d e < b- > d-"

32 PLAY "f < a > c < f a > c f < a > c < f a > c"
33 PLAY "e- < a > c < f a > c e- < a > c < f a > c"
34 PLAY "d < a- b f a- b > d < a- b f a- b"
35 PLAY "> d- < g b- e g b- > d- < g b- e g b-"
36 PLAY "> c < g- a e- g- a > c < g- a e- g- a"
37 PLAY "b f a- d f a- b f a- d f a-"
38 PLAY "b - e g d- e g b- e g d- e g"
39 PLAY "a e- g- c e- g- a e- g- c e- g-"
40 PLAY "g d- e < b- > d- e g d- e < b- > d- e"
41 PLAY "a c e- < g- > c e- < f > c e- a c e-"
42 PLAY "b- < b- > d- < g- b- > d- < f b- > d- b- < b- > d-"
43 PLAY "> c < < a > c < g- a > c < f a > c > c < < a > c"
44 PLAY "> d- <  < a b- g- a b- f a b- > > d- < < a b-"
45 PLAY "> > e < < g b- d- g b- c g b- > > e < < g b-"
46 PLAY "> > f < < a > c < < g- > a > c < < f > a > c > e- < < a > c"
47 PLAY "> d- < < a b- e a b- f a b- < f > a b-"
48 PLAY "< b- > > d f b- > d f l2 b-"

PLAY "P4"

NEXT u

