20 CLS
PLAY "ml"
INPUT nth$
25 FOR g = 1 TO 8
30 PLAY "l2n0"
40 NEXT g
50 PLAY "o3l2dc+<bagf+gl4a>c+"
60 PLAY "l2f+edc+<bab>c+"
70 PLAY "l4df+agf+df+ed<b>dagbag"
80 PLAY "l8f+a>df+e<a>c+ed<f+b>dc+<f+a>c+<bdgbadf+abdgb>c+<ea>c+"
90 PLAY "d<f+a>dc+<ea>c+<bdf+bac+f+ag<b>dgf+<a>df+g<b>dge<a>c+e"
100 PLAY "<n0f+a>dn0<ea>c+<n0df+bn0c+f+an0dgbn0f+a>dn0<gb>dn0<a>c+e"
110 PLAY "l8al16f+gl8al16f+ga<ab>c+def+gl8f+l16del8f+<l16f+gabagaf+gal8gl16bal8gl16f+ef+edef+gabl8gl16bal8bl16>c+d<ab>c+def+ga"
120 PLAY "l8f+l16dc+l8d<f+al16abl8>c+<af+>l16del8f+df+l16f+el8dc+<bl16bal8b>c+dl16f+el8df+gl16dc+l8<bbaeaa"
130 PLAY "l8def+gaeagf+bagagf+ed<b>b>c+dc+<bagf+ebabag"
140 PLAY "l8f+a>df+e<a>c+ed<f+b>dc+<f+a>c+<bdgbadf+abdgb>c+<ea>c+"
150 PLAY "d<f+a>dc+<ea>c+<bdf+bac+f+ag<b>dgf+<a>df+g<b>dge<a>c+e"
160 PLAY "l1>d"

