20 CLS
INPUT nth
22 FOR y = 1 TO 2
25 FOR g = 1 TO 8
30 PLAY "l2n0"
40 NEXT g
45 NEXT y
50 PLAY "o3l2dc+<bagf+gl4a>c+"
60 PLAY "<l4d>dl2c+<bal4dl8del4f+ab>ddc+"
70 PLAY "dl2<f+l4ed>l2dl4c+<l2bl4>d<al2ba"
80 PLAY ">l8dc+d<dc+aef+d>dc+<b>c+f+abgf+egf+edc+<bagf+egf+e"
90 PLAY "l4d>dl2c+<bal4dl8del4f+ab>ddc+"
100 PLAY "l4d<a>c+<abf+af+gdf+dgda>c+"
110 PLAY "<l4d>dl2c+<bal4dl8del4f+ab>ddc+"
120 PLAY "dl2<f+l4ed>l2dl4c+<l2bl4>d<al2ba"
130 PLAY "<l4d>dl2c+<bal4dl8del4f+ab>ddc+"
140 PLAY "l8dc+d<dc+aef+d>dc+<b>c+f+abgf+egf+edc+<bagf+egf+e"
150 PLAY "l1a"

