20 CLS
PLAY "ml"
INPUT nth
22 FOR y = 1 TO 2
25 FOR g = 1 TO 8
30 PLAY "l2n0"
40 NEXT g
45 NEXT y
50 PLAY "o3l2dc+<bagf+gl4a>c+"
60 PLAY "<l4d>dc+c+<bbaadl8del4f+ab>ddc+"
70 PLAY "l8ddl8<f+f+f+f+eedd>ddddc+c+<bbbb>dd<aabbbbaaaa"
80 PLAY ">l8dc+d<dc+aef+d>dc+<b>c+f+abgf+egf+edc+<bagf+egf+e"
90 PLAY "o3l8dd>ddc+c+c+c+<bbbbaaaaddl8def+f+aabb>ddddc+c+"
100 PLAY "dd<aa>c+c+<aabbf+f+aaf+f+ggddf+f+ddggddaa>c+c+"
110 PLAY "o3l8dd>ddl8c+c+c+c+<bbbbaaaaddl8def+f+aabb>ddddc+c+"
120 PLAY "l8dd<f+f+f+f+eedd>ddddc+c+<bbbb>dd<aabbbbaaaa"
130 PLAY "<dd>ddc+c+c+c+<bbbbaaaaddl8def+f+aabb>ddddc+c+"
140 PLAY "l8dc+d<dc+aef+d>dc+<b>c+f+abgf+egf+edc+<bagf+egf+e"
150 PLAY "l1a"

